<?php

namespace Database\Seeders;

use App\Models\Ad;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AdSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ads = [
          [
              'value' => '["&lt;!-- Yandex.RTB R-A-989341-23 --&gt;\\n&lt;div id=&quot;yandex_rtb_R-A-989341-23&quot;&gt;&lt;\/div&gt;\\n&lt;script&gt;window.yaContextCb.push(()=&gt;{\\n  Ya.Context.AdvManager.render({\\n    renderTo: &quot;yandex_rtb_R-A-989341-23&quot;,\\n    blockId: &quot;R-A-989341-23&quot;\\n  })\\n})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-27 --&gt;\\n&lt;div id=&quot;yandex_rtb_R-A-989341-27&quot;&gt;&lt;\/div&gt;\\n&lt;script&gt;window.yaContextCb.push(()=&gt;{\\n  Ya.Context.AdvManager.render({\\n    renderTo: &quot;yandex_rtb_R-A-989341-27&quot;,\\n    blockId: &quot;R-A-989341-27&quot;\\n  })\\n})&lt;\/script&gt;"]',
              'type' => 'additional_mob'
          ],
            [
                'value' => '',
                'type' => 'rubrica2_desc'
            ],
            [
                'value' => '["&lt;!-- Yandex.RTB R-A-989341-12 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-12&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-12&quot;,    blockId: &quot;R-A-989341-12&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-12 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-12&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-12&quot;,    blockId: &quot;R-A-989341-12&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-13 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-13&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-13&quot;,    blockId: &quot;R-A-989341-13&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-14 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-14&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-14&quot;,    blockId: &quot;R-A-989341-14&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-15 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-15&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-15&quot;,    blockId: &quot;R-A-989341-15&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-16 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-16&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-16&quot;,    blockId: &quot;R-A-989341-16&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-17 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-17&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-17&quot;,    blockId: &quot;R-A-989341-17&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-18 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-18&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-18&quot;,    blockId: &quot;R-A-989341-18&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-19 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-19&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-19&quot;,    blockId: &quot;R-A-989341-19&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-20 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-20&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-20&quot;,    blockId: &quot;R-A-989341-20&quot;  })})&lt;\/script&gt;"]',
                'type' => 'rubrica2_mob'
            ],
            [
                'value' => '["&lt;!-- Yandex.RTB R-A-989341-24 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-24&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-24&quot;,    blockId: &quot;R-A-989341-24&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-25 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-25&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-25&quot;,    blockId: &quot;R-A-989341-25&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-26 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-26&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-26&quot;,    blockId: &quot;R-A-989341-26&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-31 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-31&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-31&quot;,    blockId: &quot;R-A-989341-31&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-32 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-32&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-32&quot;,    blockId: &quot;R-A-989341-32&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-33 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-33&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-33&quot;,    blockId: &quot;R-A-989341-33&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-34 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-34&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-34&quot;,    blockId: &quot;R-A-989341-34&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-35 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-35&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-35&quot;,    blockId: &quot;R-A-989341-35&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-36 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-36&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-36&quot;,    blockId: &quot;R-A-989341-36&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-37 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-37&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-37&quot;,    blockId: &quot;R-A-989341-37&quot;  })})&lt;\/script&gt;"]',
                'type' => 'end_text_desc'
            ],
            [
                'value' => '["&lt;!-- Yandex.RTB R-A-989341-28 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-28&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-28&quot;,    blockId: &quot;R-A-989341-28&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-29 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-29&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-29&quot;,    blockId: &quot;R-A-989341-29&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-30 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-30&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-30&quot;,    blockId: &quot;R-A-989341-30&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-46 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-46&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-46&quot;,    blockId: &quot;R-A-989341-46&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-47 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-47&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-47&quot;,    blockId: &quot;R-A-989341-47&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-48 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-48&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-48&quot;,    blockId: &quot;R-A-989341-48&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-49 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-49&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-49&quot;,    blockId: &quot;R-A-989341-49&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-50 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-50&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-50&quot;,    blockId: &quot;R-A-989341-50&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-51 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-51&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-51&quot;,    blockId: &quot;R-A-989341-51&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-52 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-52&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-52&quot;,    blockId: &quot;R-A-989341-52&quot;  })})&lt;\/script&gt;"]',
                'type' => 'end_text_mob'
            ],
            [
                'value' => '["&lt;!-- Yandex.RTB R-A-989341-38 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-38&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-38&quot;,    blockId: &quot;R-A-989341-38&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-39 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-39&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-39&quot;,    blockId: &quot;R-A-989341-39&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-39 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-39&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-39&quot;,    blockId: &quot;R-A-989341-39&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-40 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-40&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-40&quot;,    blockId: &quot;R-A-989341-40&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-41 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-41&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-41&quot;,    blockId: &quot;R-A-989341-41&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-42 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-42&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-42&quot;,    blockId: &quot;R-A-989341-42&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-43 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-43&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-43&quot;,    blockId: &quot;R-A-989341-43&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-44 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-44&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-44&quot;,    blockId: &quot;R-A-989341-44&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-45 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-45&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-45&quot;,    blockId: &quot;R-A-989341-45&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-57 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-57&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-57&quot;,    blockId: &quot;R-A-989341-57&quot;  })})&lt;\/script&gt;"]',
                'type' => 'steps_desc'
            ],[
                'value' => '["&lt;!-- Yandex.RTB R-A-989341-53 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-53&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-53&quot;,    blockId: &quot;R-A-989341-53&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-54 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-54&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-54&quot;,    blockId: &quot;R-A-989341-54&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-55 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-55&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-55&quot;,    blockId: &quot;R-A-989341-55&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-56 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-56&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-56&quot;,    blockId: &quot;R-A-989341-56&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-67 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-67&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-67&quot;,    blockId: &quot;R-A-989341-67&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-68 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-68&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-68&quot;,    blockId: &quot;R-A-989341-68&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-69 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-69&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-69&quot;,    blockId: &quot;R-A-989341-69&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-70 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-70&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-70&quot;,    blockId: &quot;R-A-989341-70&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-71 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-71&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-71&quot;,    blockId: &quot;R-A-989341-71&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-72 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-72&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-72&quot;,    blockId: &quot;R-A-989341-72&quot;  })})&lt;\/script&gt;"]',
                'type' => 'steps_mob'
            ],[
                'value' => '["&lt;amp-ad width=&quot;300&quot; height=&quot;250&quot;    type=&quot;yandex&quot;    data-block-id=&quot;R-A-397448-36&quot;    data-html-access-allowed=&quot;true&quot;&gt;&lt;\/amp-ad&gt;","&lt;amp-ad width=&quot;300&quot; height=&quot;250&quot;    type=&quot;yandex&quot;    data-block-id=&quot;R-A-397448-37&quot;    data-html-access-allowed=&quot;true&quot;&gt;&lt;\/amp-ad&gt;","&lt;amp-ad width=&quot;300&quot; height=&quot;250&quot;    type=&quot;yandex&quot;    data-block-id=&quot;R-A-397448-42&quot;    data-html-access-allowed=&quot;true&quot;&gt;&lt;\/amp-ad&gt;","&lt;amp-ad width=&quot;300&quot; height=&quot;250&quot;    type=&quot;yandex&quot;    data-block-id=&quot;R-A-397448-41&quot;    data-html-access-allowed=&quot;true&quot;&gt;&lt;\/amp-ad&gt;","&lt;amp-ad width=&quot;300&quot; height=&quot;250&quot;    type=&quot;yandex&quot;    data-block-id=&quot;R-A-397448-40&quot;    data-html-access-allowed=&quot;true&quot;&gt;&lt;\/amp-ad&gt;"]',
                'type' => 'recipe_amp'
            ],
            [
                'value' => '{"0":"&lt;!-- Yandex.RTB R-A-989341-73 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-73&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-73&quot;,    blockId: &quot;R-A-989341-73&quot;  })})&lt;\/script&gt;","2":"&lt;!-- Yandex.RTB R-A-989341-74 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-74&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-74&quot;,    blockId: &quot;R-A-989341-74&quot;  })})&lt;\/script&gt;","3":"&lt;!-- Yandex.RTB R-A-989341-75 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-75&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-75&quot;,    blockId: &quot;R-A-989341-75&quot;  })})&lt;\/script&gt;","4":"&lt;!-- Yandex.RTB R-A-989341-76 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-76&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-76&quot;,    blockId: &quot;R-A-989341-76&quot;  })})&lt;\/script&gt;","5":"&lt;!-- Yandex.RTB R-A-989341-77 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-77&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-77&quot;,    blockId: &quot;R-A-989341-77&quot;  })})&lt;\/script&gt;"}',
                'type' => 'recipe_mobile'
            ],
            [
                'value' => '["&lt;!-- Yandex.RTB R-A-989341-61 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-61&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-61&quot;,    blockId: &quot;R-A-989341-61&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-77 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-77&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-77&quot;,    blockId: &quot;R-A-989341-77&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-1575628-70 --&gt;&lt;div id=&quot;yandex_rtb_R-A-1575628-70&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-1575628-70&quot;,    blockId: &quot;R-A-1575628-70&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-62 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-62&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-62&quot;,    blockId: &quot;R-A-989341-62&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-78 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-78&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-78&quot;,    blockId: &quot;R-A-989341-78&quot;  })})&lt;\/script&gt;"]',
                'type' => 'rubrica_desctop'
            ],
            [
                'value' => '{"0":"&lt;!-- Yandex.RTB R-A-989341-58 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-58&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-58&quot;,    blockId: &quot;R-A-989341-58&quot;  })})&lt;\/script&gt;","2":"&lt;!-- Yandex.RTB R-A-989341-59 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-59&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-59&quot;,    blockId: &quot;R-A-989341-59&quot;  })})&lt;\/script&gt;","3":"&lt;!-- Yandex.RTB R-A-989341-60 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-60&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-60&quot;,    blockId: &quot;R-A-989341-60&quot;  })})&lt;\/script&gt;","4":"&lt;!-- Yandex.RTB R-A-989341-62 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-62&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-62&quot;,    blockId: &quot;R-A-989341-62&quot;  })})&lt;\/script&gt;","5":"&lt;!-- Yandex.RTB R-A-989341-63 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-63&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-63&quot;,    blockId: &quot;R-A-989341-63&quot;  })})&lt;\/script&gt;"}',
                'type' => 'recipe_desctop'
            ],
            [
                'value' => '["&lt;!-- Yandex.RTB R-A-989341-63 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-63&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-63&quot;,    blockId: &quot;R-A-989341-63&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-79 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-79&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-79&quot;,    blockId: &quot;R-A-989341-79&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-1575628-41 --&gt;&lt;div id=&quot;yandex_rtb_R-A-1575628-41&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-1575628-41&quot;,    blockId: &quot;R-A-1575628-41&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-64 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-64&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-64&quot;,    blockId: &quot;R-A-989341-64&quot;  })})&lt;\/script&gt;","&lt;!-- Yandex.RTB R-A-989341-80 --&gt;&lt;div id=&quot;yandex_rtb_R-A-989341-80&quot;&gt;&lt;\/div&gt;&lt;script&gt;window.yaContextCb.push(()=&gt;{  Ya.Context.AdvManager.render({    renderTo: &quot;yandex_rtb_R-A-989341-80&quot;,    blockId: &quot;R-A-989341-80&quot;  })})&lt;\/script&gt;"]',
                'type' => 'rubrica_mobile'
            ],
            [
                'value' => '["&lt;amp-ad width=&quot;300&quot; height=&quot;250&quot;    type=&quot;yandex&quot;    data-block-id=&quot;R-A-397448-36&quot;    data-html-access-allowed=&quot;true&quot;&gt;&lt;\/amp-ad&gt;","&lt;amp-ad width=&quot;300&quot; height=&quot;250&quot;    type=&quot;yandex&quot;    data-block-id=&quot;R-A-397448-37&quot;    data-html-access-allowed=&quot;true&quot;&gt;&lt;\/amp-ad&gt;","&lt;amp-ad width=&quot;300&quot; height=&quot;250&quot;    type=&quot;yandex&quot;    data-block-id=&quot;R-A-397448-42&quot;    data-html-access-allowed=&quot;true&quot;&gt;&lt;\/amp-ad&gt;","&lt;amp-ad width=&quot;300&quot; height=&quot;250&quot;    type=&quot;yandex&quot;    data-block-id=&quot;R-A-397448-41&quot;    data-html-access-allowed=&quot;true&quot;&gt;&lt;\/amp-ad&gt;","&lt;amp-ad width=&quot;300&quot; height=&quot;250&quot;    type=&quot;yandex&quot;    data-block-id=&quot;R-A-397448-40&quot;    data-html-access-allowed=&quot;true&quot;&gt;&lt;\/amp-ad&gt;"]',
                'type' => 'rubrica_amp'
            ]
        ];

        foreach ($ads as $ad) {
            Ad::create($ad);
        }
    }
}
