<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Author;

class AuthorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $authors = [
            [
                'id' => '627',
                'name' => 'Ольга Федоринчик',
                'password' => '$2y$10$LxzwPMFDzIvYhB6Ps0yhIOfAc.X2CaTLUYE8.Kr9okLVhKEf7che2',
                'email' => 'saharok10@yandex.ru',
                'news_email' => 'saharok12220@yandex.ru',
                'rank' => '0',
                'news' => '1',
                'in_rating' => '1',
                'is_active' => '1',
                'is_author' => '1',
                'opit' => 'Хачу работать!',
                'primer' => 'ПОка нет',
                'oplata' => 'Криптой',
            ],
            [
                'id' => '1085',
                'name' => 'Юлия Загоруйко',
                'password' => '$2y$10$XRBdkOj.XERu5gbCWLK98eX4cuCnuJMVKZgbEApeh/De/hFZulY42',
                'email' => 'Capitoline7.nevj@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/597951.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1086',
                'name' => 'Александра Постникова',
                'password' => '$2y$10$nHfm0/Qw8WCHlWQsUh5s0OwaI7o5V5NpH6dzQSKQKZ6vbL7qw9LD6',
                'email' => 'Autonomous.Danilov8@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/43421tYtnqYzRnEYfvPt.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1087',
                'name' => 'Ирина Громова',
                'password' => '$2y$10$sgxesp0KnyxdhMA0K4Jl/ODQ6ZPQfCFytVjMdNjL55qYNA6T9IEg2',
                'email' => 'Vasily.Gorbunov0iu83@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/428352.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1088',
                'name' => 'Тамара Каданцева',
                'password' => '$2y$10$hTxUuXs.K/k.KuAY7MhSGuEI6hRGjnUc8BvH/LDQJBZO7TIoGf3Su',
                'email' => 'Tamara8.yils@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/36664sVqumS6iYnuBiAT.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1089',
                'name' => 'Ирина Завадская',
                'password' => '$2y$10$lh2EBZQ3Ni.oqAZ3TeGoue5FyenoFzBGQtOi2EPa/oedkNZAxC38q',
                'email' => 'Andrian.Danilov05o12@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/66005QfpLuZqyDU9kC7V_QGcM2Q66RRz_2BrXjf57bOkkt3NINkqBteX1cIyvzsbPm1wi1yLAEprW44e114nPs9l9bh-.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1090',
                'name' => 'Дарья Шевченко',
                'password' => '$2y$10$msKxbMJHqLU/hGyfqVOLUurTE3adGy62bOF1uJs79yxUoPvcpFtby',
                'email' => 'vorobjeva.adele@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/853238BCnEmyxOTgS1HLJ.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1091',
                'name' => 'Екатерина Кулеш',
                'password' => '$2y$10$/DQZPjBcL1swv1L2FFRKOOyi9WHXONo2Qf1SmR3bjMsrbKdP7fBD6',
                'email' => 'Marianna2.xalc@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/754949vgFjfmvkJn0A0Ad.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1092',
                'name' => 'Татьяна Трощенко',
                'password' => '$2y$10$wzw2bnwLIFaLUfrlJiKXhOxmTcG1FIpdHOr2dcXQkZ22yAmFuqaWm',
                'email' => 'volckowa.muz@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/644310013.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1093',
                'name' => 'Екатерина Литвиненко',
                'password' => '$2y$10$d4NZZKQLibUb9sITHB3G.uKzz./2inMdQ2Eoh5ARCjEHFVNAbBiLK',
                'email' => 'Sveta6.tovx@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/6029299px_ru_avatar_136993_oranjevaja_bmv__bmw_iz_igri_need_for.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1094',
                'name' => 'Анастасия Орлова',
                'password' => '$2y$10$7n2hSCWin.F1Hj2BSYN8.uwsmxMYql0ZSWwN0oTwT8WJjrtUXHmIG',
                'email' => 'amaliah.mironowa@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/2367099px_ru_avatar_171459_devushka_v_beloj_rubashke_sidit_v_avtomobile.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1095',
                'name' => 'Ангелина Токарева',
                'password' => '$2y$10$fl3EfwjD8vobBUeBNgiAveBcW3wcPbxqGBsckdXZ0eFFrEkt.m6q6',
                'email' => 'Roksana7.gonx@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/2943899px_ru_avatar_164476_brunetka_v_solnechnih_ochkah_v_belom_plate_idet.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1096',
                'name' => 'Диана Зубова',
                'password' => '$2y$10$iwhKOPmf2WqI6NJQhIpHf.6Q4bmvMOxR6raN.Tg..baic1p5giRAG',
                'email' => 'Tamara0.yeth@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/6628399px_ru_avatar_215635_ulica_v_gorode_s_fonarjami_i_osennimi_derevjami.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1097',
                'name' => 'Дарья Андреева',
                'password' => '$2y$10$VZ/SKLQqQqX1Vw2YyswuZ.JPCuxZrET0plIMH6kg3Lvu1ooumvSnq',
                'email' => 'Natasha7.nudt@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/731899px_ru_avatar_216140_v_rukah_s_varejkami_krasnaja_chashka.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1098',
                'name' => 'Юлия Вязовская',
                'password' => '$2y$10$laIod1u.BOPebghHDTpXku7kAm4kYfekQrj.nV6vRT/N.9nM0s/Ya',
                'email' => 'Patricia7.mopr@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/572799px_ru_avatar_216141_devochka_so_shenkom_na_klavishah_pianino_pod_padaushej.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1099',
                'name' => 'Анастасия Клинская',
                'password' => '$2y$10$LCH3qh0f1px.PjgOPfIwbeawLExvE9kfnhnSUg/7P2673SuGM0E6a',
                'email' => 'adelsherbakowa@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/5136199px_ru_avatar_216144_pes_v_novogodnem_kolpake_s_visunutim_jazikom.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1100',
                'name' => 'Любовь Павловна',
                'password' => '$2y$10$IN.6OhhSRs0mtlJLDc/PT.eavpCSqysH5.2JneSknw31F4zb2h05C',
                'email' => 'Natasha2.qivy@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/1611999px_ru_avatar_216147_portret_devushki_s_belimi_rozami_i_belimi_lepestkami.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1101',
                'name' => 'Светлана Шлыкова',
                'password' => '$2y$10$zEHTn4J2KuEaXgEpYgy7heeFaQqZrWRmUNZgD/vt/Ht7VgLAV.WzG',
                'email' => 'Aurora0.guqn@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/627841016.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1102',
                'name' => 'Лариса Николаевна',
                'password' => '$2y$10$5mvzrILBTcZ9dkOuGven2.spmHnShJTPZUUen7/0ITIgXY2UC4NsG',
                'email' => 'eremei.kalininitch@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/929451036.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1103',
                'name' => 'Оля Гаврилова',
                'password' => '$2y$10$gwf9ECJGdBS4Ep85rcCBYOh9.l4VFAZElK8pMlXQKc148vEnwgHvC',
                'email' => 'lev.belozyorovitch@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/363741760.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1104',
                'name' => 'Ольга Игнатенко',
                'password' => '$2y$10$Tt3X.f55LcuAAQaFLofyne5ZUUmhS7/0VX5CvtKGuq08xcs9u5jAe',
                'email' => 'Veronica9.qapr@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/989863358.gif',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1105',
                'name' => 'Галина Куликова',
                'password' => '$2y$10$8.FoNcjW7E69L0/uQ/lLjuhJMTYpnf9AUZkCQ3f2/mycJu9z5N8DO',
                'email' => 'evstafy.gavrilov@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/95598103592.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1106',
                'name' => 'Светлана Баринова',
                'password' => '$2y$10$LDbAQKA2tLS2yFQhoIf5POcR3T3eZh8u0ikR6RepnBbZ5Ee6Wc91O',
                'email' => 'vorobyovitch.anton@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/6961103968.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1107',
                'name' => 'Оксана Орлова',
                'password' => '$2y$10$yLyVeWTaKtCCAU7K/ERC3u/G43WE3b3X1DFiRufaKYxb2.5Vj9q/G',
                'email' => 'bobrowa.rock@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/74015104214.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1108',
                'name' => 'Полина Сальникова',
                'password' => '$2y$10$Ywfk7oQfpDMHZ5PcDpk8O.QH8v6fcKe2m9fGUgSSr3L5r2zc3F92S',
                'email' => 'Emma8.kevs@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/5888104322.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1109',
                'name' => 'Виктория Лазарева',
                'password' => '$2y$10$CMYEs..FuQIXw8.JLPYKL.MwoaM9aMQjpY3kF2azK/LFo6YduIxom',
                'email' => 'bori5lav.egorov@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/805430139850.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1110',
                'name' => 'Виктория Шаповалова',
                'password' => '$2y$10$kh/jvkcvXzzCtXKro.bZB./i1qVHUc6RHObbxTrxQvh3kj0N4iZvS',
                'email' => 'basilmolchanovitch@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/576760367953.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1111',
                'name' => 'Светлана Несмеянова',
                'password' => '$2y$10$RsXmIrfONL.WhhDdxIgDE.bZx.IvncEgVc0xB/7r2SflrkYH6ME.a',
                'email' => 'peter.danilovich@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/494010937613.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1112',
                'name' => 'Андрей Бирюков',
                'password' => '$2y$10$fZ7XOb/DnEYNyXieyAILMOixFGoBYpZyhtnaMpBRy.UkEsgWZ2xu2',
                'email' => 'Avdey.Biryukov1@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/601970729588.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1113',
                'name' => 'Юлия Дорохова',
                'password' => '$2y$10$5NFpEOaJlvHkdWb8LwbKVOha7hFzoGtVYH/qsAu6YPOHVhLvqqcu2',
                'email' => 'Elvira8.jodz@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/294271236657.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1114',
                'name' => 'Елена Бажухина',
                'password' => '$2y$10$FBqkWPfvuedizyNLpwd1mO04lDVDhLDmV1JjRlI4sh1Y9lMYe4OjC',
                'email' => 'emelyanevseevitch@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/884551435171.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1115',
                'name' => 'Ольга Пронькина',
                'password' => '$2y$10$GDJn/Z6QGeVDT1KX3UR13e9yiuEtYKESz8fkqBwkGTypYrQ.0dLjK',
                'email' => 'averky.ermakovitch@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/147101697792.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1116',
                'name' => 'Наталья Вязникова',
                'password' => '$2y$10$y627QA3jK9I5IIpjKRy4IePdfFsy4SNZUTgGvuSd3PnYimfUPOTUi',
                'email' => 'Sveta2.givr@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/20702169494.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1117',
                'name' => 'Вероника Левина',
                'password' => '$2y$10$m9W/pIURmBStlwS14cIAHuIeuOgRwIfD875I.SemH5ZWMO7nd2T82',
                'email' => 'Vadim.Danilov3@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/416822736116.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1118',
                'name' => 'Даша Вишневская',
                'password' => '$2y$10$e7dpU9sJb1MrXi6LFPwxtO6OiLiIw0Ov62kIeMl9z8Hf24MfPCp/K',
                'email' => 'petuhovacapitolina@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/317763764623.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1119',
                'name' => 'Елена Туровская',
                'password' => '$2y$10$N5qRp/w96jSQ55a1X7WZu.cXMVmJ/gbQRxGPTRWWchB3sedng9x.6',
                'email' => 'egorovitchvadik@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/708563964034.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1120',
                'name' => 'Людмила Костенко',
                'password' => '$2y$10$IFzFYeeG9pnJXCqURskuOuz6rEcKBnax3U9iQy8jqaxZcmpEIBc9e',
                'email' => 'Venus9.tufn@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/558664990850.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1121',
                'name' => 'Марина Давыдова',
                'password' => '$2y$10$sNG3QS3xV0BGuJ45XjrxOOFLK3i3hzWD6HHahkaBlG.W1BoWoiyWm',
                'email' => 'evstafy.golubev@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/729595484094.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1122',
                'name' => 'Елена Пирогова',
                'password' => '$2y$10$2CYJRQEF3j6pa06W27gMqOMNkfa0dEfQv9Ms.V9CqrrUvBxgEwPXq',
                'email' => 'novikowaadelaida@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/362775598451.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1123',
                'name' => 'Надежда Цыбуляева',
                'password' => '$2y$10$WwW8tPtWPZQXep9o1H/rGehCqE95HVyvtt5VGr1nnrzjM45G921n6',
                'email' => 'Oksana1.pubk@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/585106119887.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1124',
                'name' => 'Елена Гнедова',
                'password' => '$2y$10$kl7qiNCiXGZKywHKIyIhP.2.s2o2Zxm.fz7VsFalgVVUm0Inbd1x2',
                'email' => 'Juliana6.hobp@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/732186181964.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1125',
                'name' => 'Ирина Винокурова',
                'password' => '$2y$10$yN5AYzDXwYsmAQ9VuDKXwujfRai1eLUYYerDLfNYpFytJXDVP0HRq',
                'email' => 'iefim.dorofeev@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/600156237455.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1126',
                'name' => 'Галина Садовникова',
                'password' => '$2y$10$JZP1Qo4nsLAScs3RYsTmyOA0b1su9pbK8TqjXcmlohzRq..7lKjLy',
                'email' => 'Grigory.Danilov4@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/281306315234.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1127',
                'name' => 'Светлана Костюченко',
                'password' => '$2y$10$1joPOBOPXz9FlbrGqDwr2OyjP.A1b.bSCzSCkaIBVJJ9wHXGc3C0.',
                'email' => 'Pelagia3.fejy@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/642816459107.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1128',
                'name' => 'Ирина Муромцева',
                'password' => '$2y$10$3O4VbXOvDN9OnfAI8LliPuFg7b0cNO9TFpECdeS5YWt5xFWvNRaUe',
                'email' => 'Vyacheslav.Belozerov7@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/942466576124.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1129',
                'name' => 'Наталья Филасева',
                'password' => '$2y$10$G/aYXUETAulwXLqBsV7Ch.62R3.Ea4oPtqrJqycS14g5mEUPIsFj2',
                'email' => 'tarasova.1zolda@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/281726576124.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1130',
                'name' => 'Катерина Полякова',
                'password' => '$2y$10$Hbb9Kf1pdo.8ht8F9QR2zufjYr5Sw/IRHR39gvAW/TkTeiaLDlgmK',
                'email' => 'egor.ivanckovitch@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/861736639673.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1131',
                'name' => 'Татьяна Журавлева',
                'password' => '$2y$10$XulYdntOrYjRhHAjtnIkw.i.NXSEDMOCyjbDOntnndIQ6o7JnNgCO',
                'email' => 'grigory.ermakovitch@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/722826885616.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1132',
                'name' => 'Наталья Малышко',
                'password' => '$2y$10$uY/esO728F3Ww8VjX2ImUunUDc4ccSkN8gp86iKmNRIxN/o6erU8i',
                'email' => 'antonowa.venercka@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/134817127571.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1133',
                'name' => 'Виктория Гунькина',
                'password' => '$2y$10$r91OTNB5P6yZ9z.Uq1Qwj.umzWuXWSb7o9aTy239Z5/5EI5p.73NW',
                'email' => 'Eliza6.qekb@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/634147140904.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1134',
                'name' => 'Светлана Беляева',
                'password' => '$2y$10$jjNEOS0NZ2L.CgidKLgJIOafQXJWOogFxA7WQaojPTteVVH6oo60.',
                'email' => 'Valery.Artemyev077@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/657457144716.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1135',
                'name' => 'Нина Гавриленко',
                'password' => '$2y$10$snOD4SEkg6MD.jRfxoFgq.3GZb2v/ERWhJcUxFT39qEQ4BEPxAQIO',
                'email' => 'Ilona3.lipw@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/728917208069.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1136',
                'name' => 'Алла Антонова',
                'password' => '$2y$10$ofGakkL8H5TqjX.7kHiF5uRKmILkjwYKotmbUy/fijn6GAMDJr6FW',
                'email' => 'Vladimir.Doronin5@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/489677783406.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1137',
                'name' => 'Нина Анатольевна',
                'password' => '$2y$10$w8ug2lSQbgjWZXHRi8xvL.JotDa4UiOR2xYZVGzRBVDnNcF0YFLfu',
                'email' => 'Clara8.loxm@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/670398447465.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1138',
                'name' => 'Наталья Полтавцева',
                'password' => '$2y$10$v47URYUOAUk.QM5Yx.IhA.j6prELoBf0YY0fi1m6miWKRwDChUFBC',
                'email' => 'Emma5.teql@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/932338536423.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1139',
                'name' => 'Татьяна Нестеренко',
                'password' => '$2y$10$VOz7VtUn/5P3unbo0.xsI.8cG8gFAk4NvzrH/moXAcCfL.6o24vlG',
                'email' => 'nickgerasimowitch@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/931138553887.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1140',
                'name' => 'Екатерина Могилевская',
                'password' => '$2y$10$3gaTl89gxxyrz9/WQX7mS.tj94kimcpRwOhXUH.rf.DWUIeGzGe7O',
                'email' => 'semenbelozyorovitch@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/898868617091.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1141',
                'name' => 'Ирина Ермилова',
                'password' => '$2y$10$/t5kn7ksx97/oh3B3OfLO.DQ0DWOblnE6ASNdIt3TrYMMZtmXgIrO',
                'email' => 'gl4fira.kalinina@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/995578787081.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1142',
                'name' => 'Марина Харина',
                'password' => '$2y$10$1uMmFNfy.hyNZ1Cxx44fpOQU8DumVDtoaxlB8RWWCKvQZr50gLw9q',
                'email' => 'Pelagia7.yokz@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/578329264842.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1143',
                'name' => 'Татьяна Шишлова',
                'password' => '$2y$10$i7GprtNsCRNRo4hH42Grn.RR/CGXVqAHb/Fk.6hyvKHYw.DbU81/y',
                'email' => 'Lucien0.vonm@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/94539957765.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1144',
                'name' => 'Вероника Филатова',
                'password' => '$2y$10$RKo9AR5Q4CrJRtwo9SthBePFCQB9Yn4fpR/mkx1Er9/qdSlu4TyAu',
                'email' => 'Albina4.wick@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/19020AidoJKVmpxdwgEOxkIWwiPjl0bIjI5F2Tuu0PlditTVEHKnAZYJ5040YqUUb2GzyxhOwtUoSdVxMsFK8kAGbpO3F.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1145',
                'name' => 'Валерия Воронцова',
                'password' => '$2y$10$A8KGmKbaMZ4G.vPvf1P2PenV46oCowkT35iNjMCdcNl.4ucsN08q6',
                'email' => 'taisia8.capx@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/1481ava_34317_1439623632.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1146',
                'name' => 'Валентина Лихачева',
                'password' => '$2y$10$Fq5/GvbZFXPbjTDScOfS6./4Hxs2lnl5CidbVHeudm9EC2o/hXTTW',
                'email' => 'Alexandra3.mubz@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/65565ava_51383.1569219956.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1147',
                'name' => 'Алёна Шестакова',
                'password' => '$2y$10$EvM1aObYFBEXoXHKV0Aly.K0S2qIi.vwnrJONvAkNbptBW0K8lZoq',
                'email' => 'Anatoly.Belyaev67oa28@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/71073BZyGy5U1FQak2GBT.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1148',
                'name' => 'Оксана Колтакова',
                'password' => '$2y$10$SdoJZnxCj90pNzTyr2XSo.FvHAiEk6hHvdJP363wrSm2TRQQWk8wO',
                'email' => 'k.ignatjevitch@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/20643ch103qiSTM4PrnEh.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1149',
                'name' => 'Вероника Ильина',
                'password' => '$2y$10$6q2Jgfyol/1wj5BI0dr0XuTIMjGYR2hjyEx4nF3A8FqdgYt9dw3c6',
                'email' => 'borislavalekseevitch@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/54983DmJiWUQqH8x78tan.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1150',
                'name' => 'Татьяна Коваль',
                'password' => '$2y$10$Xwvqqkw.0rkI4wns/VzhlOS.NvY7PxNTbCfOdofjRtxi8JGXj1PX2',
                'email' => 'Aggey.Bespalov0@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/90910e7bMO7BEDXyQXdiC.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1151',
                'name' => 'Елена Савченко',
                'password' => '$2y$10$86os4EULplpA1k.OlBQ9qOFsT6bLHxxabr3OTDMDZjsSLbwm8Ts9K',
                'email' => 'evg3ny.anisimov@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/40106eIarP1H193NH8izn.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1152',
                'name' => 'Юлия Бегунова',
                'password' => '$2y$10$szkrwF.Jj92e6fX8ulkA8e0j5vz1df1ktvrbvbQwk4IeuLZAVb5mW',
                'email' => 'Marianna5.razg@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/30014EP7xD3AWzAYDTDTd.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1153',
                'name' => 'Наталья Терещенко',
                'password' => '$2y$10$n5pcsafXlqAOfo5.NQpozOxf9w9JXj.J4WVF6cm3Zy3StzSdyBWYy',
                'email' => 'Eugene0.xovr@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/61982fQAS7ZgL14NTJhui.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1154',
                'name' => 'Светлана Калинина',
                'password' => '$2y$10$XEl3JDsocEAAd/ZbRBdSo.5itgIM6t.7kdSDu.adMoO502B0cs3Qm',
                'email' => 'Andrian.Belyakov7@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/11063i (1).jfif',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1155',
                'name' => 'Виктория Фролова',
                'password' => '$2y$10$iq5RTL0DHPjS8mLaon/N7eI56E9pJ3XOYMwx1PJUI62z6vLo0MknC',
                'email' => 'Tamara3.nicx@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/12546i (2).jfif',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1156',
                'name' => 'Татьяна Субботина',
                'password' => '$2y$10$F9plWvgHCh.LKyYvFSnuMuIlbLp3OxxLEBdJ04HsDkJ5JIrlZwa.C',
                'email' => 'andriangerasimovitch@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/19194i (3).jfif',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1157',
                'name' => 'Анастасия Максимова',
                'password' => '$2y$10$maXwe5zaxObYnU57EwyGGe.csbn/XDXrcDmuiZdFo79OzwanXfG1W',
                'email' => 'gordeev.aw@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/12739i (4).jfif',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1158',
                'name' => 'Оля Хмелевская',
                'password' => '$2y$10$Q2ypzQweFQg8vFOtzs6xYetA14E0OjfdAoU7QoLMqTDOgMhxABVd.',
                'email' => 'Veronica4.gemh@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/80307i.jfif',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1159',
                'name' => 'Лариса Стрельникова',
                'password' => '$2y$10$7D54XvjkUM2smg7fnNQu2.Jegit19VcngxoVX4BQolOz4EcdVNqMm',
                'email' => 'Denis.Baranov9@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/19990iQaVPh9847L2lL4U.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1160',
                'name' => 'Ольга Жандарова',
                'password' => '$2y$10$sD2j.XpONQ6BgUAMIOipnuaFinyFDCc8IJtObbFuUg4FcFgTLl7dm',
                'email' => 'belozyorovitchaleksei@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/72438IvSQpMHRuWXjzCzY.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1161',
                'name' => 'Ксения Юрьева',
                'password' => '$2y$10$nC1FuGXBYYm9dTFgGSH24.Bj/Rq4S8TRz/lKNk5HfsXhJWNkA5uT6',
                'email' => 'pelageya.le8edeva@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/69836MHJpUV1n6AitRTT7.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1162',
                'name' => 'Светлана Литвинова',
                'password' => '$2y$10$A2Es41J4fIvB1v4z/hrdQuxaIOl8UgXw9a/VkyFjfLmuI1Xf4auua',
                'email' => 'Roksana2.molc@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/40584MQpYHOShJ5ocixfr.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1163',
                'name' => 'Надежда Кудрявцева',
                'password' => '$2y$10$p.bR9L/TtNygCIjAFj4BpuWRnSCxR5DjO.NA3yJcpaMclkPwnWjai',
                'email' => 'bellebogdanowa@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/16514Msp72deaJK8UzpRE.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1164',
                'name' => 'Ирина Шипулина',
                'password' => '$2y$10$m5HpdDikdGc2IrvbAQwFvuaV1kyW72ROa7JbqAMK7TbbuZaFgSJf2',
                'email' => 'Venus0.vafd@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/82804NGCm3q_GCWv87hNFoCdBE2PQmu3Ry_kcT4xNZEht1odWrPtJePTUeW1ZXqbxEfzPQLxD8fsonX8vQ7sz4ly1Qv5E.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1165',
                'name' => 'Евгения Черепанова',
                'password' => '$2y$10$dv8ANtHlYTe.wna7mfPRw./pEQsoKz.JD.7KQCVixGBGjWxk63iXS',
                'email' => 'ermakovi4a@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/11511NUu6bUBSthhHOZOC.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1166',
                'name' => 'Екатерина Ермошкина',
                'password' => '$2y$10$AjY4AWRxKzmYguxLHLiykO8UBszhQtQ143A.0KZUJVd3gUCrAp3.e',
                'email' => 'Oksana4.cech@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/51104nwKenZfvOFGQEL4W.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1167',
                'name' => 'Елизавета Мочалова',
                'password' => '$2y$10$O2Tv93CKBw.HRSLI6mPRYOoTnvehPewiQcp98iL.Ea67FJa0/Plu.',
                'email' => 'solovajevaglafira@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/57297o9vDHHN5AV9rLDRS.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1168',
                'name' => 'Екатерина Корнилова',
                'password' => '$2y$10$w7sUAZRLi68v7nX6ZygETOQp.u6r0cGtZMOXV5uXFsYjJJta7wPF6',
                'email' => 'averjanvolkov@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/32153OzgNqZXQlCWQx6hZ.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1169',
                'name' => 'Оксана Сизинцева',
                'password' => '$2y$10$JGTCq7PE7MOvUPjvaR0Ihu9X7QolATNdJduieyBKd0bEWLkTLatIK',
                'email' => 'Julia0.dewb@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/41845phTO7U6jGy5QrH9B.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1170',
                'name' => 'Елена Терёхина',
                'password' => '$2y$10$327Ba5cz1IEiyONpUNbM8.zE0fOEG83LVL2AM30Y7IgZElNDoKKFi',
                'email' => 'oleggerasimowich@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/61541R7vukavFeerzawrf.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1171',
                'name' => 'Валентина Радченко',
                'password' => '$2y$10$q5Z.Frm8BWmSbCu12y1a/.BCANZAta.jKh4idW8TnrSVK9MXrbMnG',
                'email' => 'Muse4.rett@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/62229rYZs0zL3qNoenbhO.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1172',
                'name' => 'Светлана Попкова',
                'password' => '$2y$10$QCHDVjoEDDV8oKzYN6LgIucDKEFS.6snKjeYRdPxQScK6tTEK8QZO',
                'email' => 'Pelagia5.mavd@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/44099SXcgVCPfIShhbpoL.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1173',
                'name' => 'Елена Сазонова',
                'password' => '$2y$10$8W3fAsHllHV/CdUhwP4S0eMsMq7bVsnx7.iR3KOZAkABRFnUX27PO',
                'email' => 'Isabella0.nugt@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/74421TTrJ4Peotib5GJhh.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1174',
                'name' => 'Наталья Кондратьева',
                'password' => '$2y$10$QyPF83P6LW.jl5ytSOnDH.ALNHO0WNxK1pq1xNkojxcvRLFdDxUe2',
                'email' => 'Eva7.pavh@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/60094VGBs2zuMB8iMlj7i.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1175',
                'name' => 'Ирина Рыленко',
                'password' => '$2y$10$Dz9Amynf6oSWny11cguuFuNlOeMNe7Zww2wiFkmeOg3TdFXimNF8a',
                'email' => 'andreeffavd@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/44291vXjbBbtsZqYRxXlI.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1176',
                'name' => 'Наталья Павленко',
                'password' => '$2y$10$EyjZDlaEu3Ne7W1VQ6ZOZOmVmzzdLl9BZ4bUHhTPp.UYfT7RZPTLy',
                'email' => 'Zlata9.xadm@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/65526XzwxEuI0UYGq5myl.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1177',
                'name' => 'Александр Виноградов',
                'password' => '$2y$10$n4I26wgba9GdUZhyd48Z0eA4kVj0QGPG25Mz3UAWZcqfAAdw6qRO6',
                'email' => 'Alexander.Vinogradov46832@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/37076w-BWmQQOyVYE5qOpD5X7Z1fLNFJH2GSDCztC8BTJcWgr1fqfANM90JoYJBdmqUIefM_AJ3oi.jpg',
                'is_active' => '1',
                'is_author' => '1',
                'currency' => '2',
            ],
            [
                'id' => '1178',
                'name' => 'Виктория Миронова',
                'password' => '$2y$10$ZKLB87dKhgtigV1SuODJEOhlSRlmILlYYxgJ5h6qDLde2wglxXR2G',
                'email' => 'artemiewadrian@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/93458YfhngVNhu20QVjRu.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1179',
                'name' => 'Галина Якупова',
                'password' => '$2y$10$5PAUw3PHN4xWOGbiXoGgPOf4B2ovxMrC8alZoNixAGQmPb6N1Vvv6',
                'email' => 'Lucien6.yohf@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/21366zLUYf2KwMD1h8ZVF.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1180',
                'name' => 'Николай Богданов',
                'password' => '$2y$10$hj0Cz1pAlzeGaMH7TY0qAudBwm5DquDV3hkZctVoHYS8PQjeJHEtm',
                'email' => 'Andrian.Bogdanov26483@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/397593867190.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1181',
                'name' => 'Давыдов Валерий',
                'password' => '$2y$10$ywVpFitQAOxJk6ZDEVB/kOc6DRTaA3M3UmTHOuUfzEzwQcKts.3HW',
                'email' => 'Valery4.Davydov8@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'photo' => '/uploads/83457534581.jpg',
                'is_active' => '1',
                'is_author' => '1',
            ],
            [
                'id' => '1212',
                'name' => 'Ольга',
                'password' => '$2y$10$Of/XB8.PVeIqwB.LgAswjeH9L0m8NB4ClnWkLMPHADbG9RBDfuTYq',
                'email' => 'gavinski12@yandex.ru',
                'news_email' => 'gavinski12@yandex.ru',
                'rank' => '0',
                'in_rating' => '1',
                'hash' => '$2y$10$j5HgtFEqpVh2/t4gpeOu4uUKbBbmJ64PDC7c.SDr/aMx5F08UBcHe',
                'is_active' => '1',
                'is_author' => '1',
                'opit' => 'есть',
                'primer' => 'есть',
                'oplata' => 'есть',
            ],
        ];

        foreach ($authors as $author) {
            Author::create($author);
        }
    }
}
